# This workflow builds the docs using pdoc and makes it available via GitHub pages.
# source: https://github.com/mitmproxy/pdoc/blob/main/.github/workflows/docs.yml

name: Build and publish docs to GitHub Pages

# build the documentation whenever there are new commits w/ tags on main
on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

# security: restrict permissions for CI jobs.
permissions:
  contents: read

jobs:
  # Build the documentation and upload the static HTML files as an artifact.
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # install all dependencies (including pdoc)
      - run: pip install -r requirements.txt
      - run: pip install -r requirements_build.txt
      - run: pip install -e .

      # build documentation into docs/.
      - run: ./scripts/build_docs.sh

      - uses: actions/upload-pages-artifact@v4
        with:
          path: docs/

  # Deploy the artifact to GitHub pages.
  # This is a separate job so that only actions/deploy-pages has the necessary permissions.
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v2

