# This workflow will install Python dependencies and run tests with a variety of OS/Python/NumPy/OpenCV versions

name: Tests (subset)

on: [push, workflow_dispatch]

jobs:

  tests:
    
    strategy:
      matrix:
        os: [ubuntu-18.04]
        python-version: ['3.6', '3.9']
        numpy-version: ['>=1.13.3,<1.21.0']
        opencv-version: ['>=3.0.0,<4.0.0', '>=4.0.0,<5.0.0']
    
    runs-on: ${{ matrix.os }}
    
    timeout-minutes: 10

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install setuptools wheel
        python3 -m pip install "numpy${{ matrix.numpy-version }}"
        python3 -m pip install "opencv-python${{ matrix.opencv-version }}"
        ./scripts/build_install_dev.sh
    - name: Run tests
      run: |
        ./scripts/run_tests.sh
