# This workflow will install Python dependencies and run tests with a variety of OS/Python/NumPy/OpenCV versions

name: Tests (full)

on: [workflow_dispatch]

jobs:

  tests:
    
    strategy:
      matrix:
        os: [ubuntu-16.04, ubuntu-18.04, ubuntu-20.04]
        python-version: ['3.5', '3.6', '3.7', '3.8', '3.9']
        numpy-version: ['==1.13.3', '']
        opencv-version: ['>=3.2.0,<3.3.0', '>=3.0.0,<4.0.0', '>=4.0.0,<5.0.0']
        exclude:
          - os: ubuntu-18.04
            python-version: '3.5'
          - os: ubuntu-20.04
            python-version: '3.5'
          - numpy-version: '==1.13.3'
            python-version: '3.7'
          - numpy-version: '==1.13.3'
            python-version: '3.8'
          - numpy-version: '==1.13.3'
            python-version: '3.9'
    
    runs-on: ${{ matrix.os }}
    
    timeout-minutes: 10

    steps:
    - name: Checkout 
      uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install setuptools wheel
        python3 -m pip install "numpy${{ matrix.numpy-version }}"
        python3 -m pip install "opencv-python${{ matrix.opencv-version }}"
        ./scripts/build_install_dev.sh
    - name: Run tests
      run: |
        ./scripts/run_tests.sh
